const GET_HOTELS_IMAGES = 'app/hotels/GET_HOTELS_IMAGES';
const GET_HOTELS_IMAGES_SUCCESS = 'app/hotels/GET_HOTELS_IMAGES_SUCCESS';
const GET_HOTELS_IMAGES_FAILURE = 'app/hotels/GET_HOTELS_IMAGES_FAILURE';

export default {
    GET_HOTELS_IMAGES,
    GET_HOTELS_IMAGES_SUCCESS,
    GET_HOTELS_IMAGES_FAILURE
};
